version: "3"

services:
  web:
    build: .
    working_dir: /web
    command: yarn dev --host 0.0.0.0 --port 3000
    volumes:
      - .:/web
    ports:
      - 4000:4000
      - 24678:24678
    environment:
      - SHELL=/bin/sh
    stdin_open: true
    tty: true

  nginx:
    image: nginx:1.23-alpine
    depends_on:
      - web
    volumes:
      - ./third_party/nginx/app-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
